package online.db.model.enums;

public enum NextCategory {

    PLASTERMIXTURES,PRIMERSCONCRETECONTACT,PUTTY,FOAMBLOCKSBRICKPGP,GYPSUMBOARDPROFILEGVL,TILEADHESIVEGROUT,BLOCKSADHESIVE,
    WATERPROOFINGANDINSULATION,SEALANTMOUNTINGFOAM,NETSPAINTINGSICKLES,ENAMELPAINTS
}
